### ISSUE TITLE
TypeError: crypto_1.X509Certificate is not a constructor

### ISSUE THREAD

**Issue by janlueders** [agisboye/app-store-server-api#42]
Hi, when I tried your package, I got the above error with every request for test-notifications.

I have posted the code [here](https://github.com/janlueders/apple-notifications/).

The exact error is this one. If I have forgotten something in the sample code, please add it here in the comments.

```
TypeError: crypto_1.X509Certificate is not a constructor
    at /node_modules/app-store-server-api/dist/cjs/Decoding.js:142:60
    at Array.map (<anonymous>)
    at validateCertificates (/node_modules/app-store-server-api/dist/cjs/Decoding.js:142:34)
    at /node_modules/app-store-server-api/dist/cjs/Decoding.js:118:29
    at step (/node_modules/app-store-server-api/dist/cjs/Decoding.js:56:23)
    at Object.next (/node_modules/app-store-server-api/dist/cjs/Decoding.js:37:53)
    at /node_modules/app-store-server-api/dist/cjs/Decoding.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/node_modules/app-store-server-api/dist/cjs/Decoding.js:27:12)
    at getKey (/node_modules/app-store-server-api/dist/cjs/Decoding.js:113:74)
```

**Comment by janlueders** [comment]
The problem is solved
